const EventType = {
  EVENT_ID_NONE: -1,
  SINGLE_CLICK: 1,
  DOUBLE_CLICK: 2,
  TAB_CHANGED: 3,
  TAB_UPDATED: 4,
  TAB_REMOVED: 5,
  WINDOW_CHANGED: 6,
  CONTENT_SCRIPT_MESSAGE: 7,
  INIT_CONTENT_SCRIPT: 8,
  CONTEXT_MENU: 9
};

export { EventType };
