const KEY_ACTION = 'action';
const KEY_COMMAND = 'command';
const KEY_DATA = 'data';

const ACTION_OPEN_MODAL = 'open_modal';
const ACTION_CLOSE_MODAL = 'close_modal';
const ACTION_START_SCROLLING = 'start_scrolling';
const ACTION_STOP_SCROLLING = 'stop_scrolling';
const ACTION_CHANGE_SPEED = 'accelerate_scrolling';
const ACTION_UPDATE_COMMAND = 'update_command';
const ACTION_INIT_CONTENT_SCRIPT = 'init_content_script';

const MESSAGE_OPEN_MODAL = { [KEY_ACTION]: ACTION_OPEN_MODAL };
const MESSAGE_CLOSE_MODAL = { [KEY_ACTION]: ACTION_CLOSE_MODAL };
const MESSAGE_START_SCROLLING = { [KEY_ACTION]: ACTION_START_SCROLLING };
const MESSAGE_STOP_SCROLLING = { [KEY_ACTION]: ACTION_STOP_SCROLLING };
const MESSAGE_CHANGE_SPEED = {
  [KEY_ACTION]: ACTION_CHANGE_SPEED,
};
const MESSAGE_UPDATE_COMMAND = { [KEY_ACTION]: ACTION_UPDATE_COMMAND };
const MESSAGE_INIT_CONTENT_SCRIPT = {
  [KEY_ACTION]: ACTION_INIT_CONTENT_SCRIPT,
};

const create = action => ({ [KEY_ACTION]: action });

const addData = (message, data) => ({
  ...message,
  [KEY_DATA]: data,
});

export {
  KEY_ACTION,
  KEY_COMMAND,
  KEY_DATA,
  ACTION_OPEN_MODAL,
  ACTION_CLOSE_MODAL,
  ACTION_START_SCROLLING,
  ACTION_STOP_SCROLLING,
  ACTION_CHANGE_SPEED,
  ACTION_UPDATE_COMMAND,
  ACTION_INIT_CONTENT_SCRIPT,
  MESSAGE_OPEN_MODAL,
  MESSAGE_CLOSE_MODAL,
  MESSAGE_START_SCROLLING,
  MESSAGE_STOP_SCROLLING,
  MESSAGE_CHANGE_SPEED,
  MESSAGE_UPDATE_COMMAND,
  MESSAGE_INIT_CONTENT_SCRIPT,
  addData,
  create,
};
